[project]
name = "minimization"
version = "0.1.0"
description = "N-dimensional free energy minimization script"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "scipy>=1.14.1",
]
